; PlatformIO project file for the SCADA ESP32 edge node.
; Build with:   pio run
; Wokwi reads the resulting firmware.bin/.elf via wokwi.toml - see README.md.

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
	emelianov/modbus-esp8266@^4.1.0
	marcoschwartz/LiquidCrystal_I2C@^1.1.4
	paulstoffregen/OneWire@^2.3.7
	milesburton/DallasTemperature@^3.11.0
